### ISSUE TITLE
Move TPL version requirements in a shared Spack Environment file

### ISSUE THREAD

**Issue by chapman39** [LLNL/serac#1244]
The following yaml is being repeated across all Spack Environment files. It should be moved to a separate yaml file.

```yaml
    # Globally lock version of third party libraries
    axom:
      require: "@0.9.0.1"
    camp:
      require: "@2024.02.0"
    conduit:
      require: "@0.9.1~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    mfem:
      require: "@4.7.0.1"
    raja:
      require: "@2024.02.0~shared~examples~exercises"
    tribol:
      require: "@0.1.0.16~examples~tests"
    umpire:
      require: "@2024.02.0~shared~examples~werror"
```
