### ISSUE TITLE
Refactor the main pipeline to use the batch partition

### ISSUE THREAD

**Issue by jamiebramwell** [LLNL/serac#228]
We cannot ask more than 30 min for a pdebug allocation (see `SLURM_ACCOUNT` value).
But pdebug was critical for `pr_workflow`. Since dependencies are built only in `main_workflow`, we could change `SLURM_ACCOUNT` not to use pdebug in that case.

My suggestion:

```
.pr_workflow:
  variables:
    SLURM_ACCOUNT: -p pdebug -A eng
    LSF_ACCOUNT: -q pdebug -G eng
  rules:
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $BUILD_DEPS != "ON"' #run only if ...

.main_workflow:
  variables:
    SLURM_ACCOUNT: -A eng
    LSF_ACCOUNT: -G eng
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" || $BUILD_DEPS == "ON"' #run only if ...
```

_Originally posted by @adrienbernede in https://github.com/LLNL/serac/pull/227#r498530376_
